//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMoolah.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLog
    {
        public int Key { get; set; }
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string Token { get; set; }
        public string Method { get; set; }
        public string Http { get; set; }
        public string Endpoint { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> StartTimeStamp { get; set; }
        public System.DateTime EndTimeStamp { get; set; }
    }
}
