//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMoolah.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAudit
    {
        public int Key { get; set; }
        public Nullable<int> ApplicationKey { get; set; }
        public string FormData { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
