//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMoolah.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAccess
    {
        public int Key { get; set; }
        public Nullable<int> ApplicationKey { get; set; }
        public string MiniApplicationReference { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
