//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMoolah.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEmail
    {
        public int Key { get; set; }
        public string EmailType { get; set; }
        public string ToAddress { get; set; }
        public string ToAddressTitle { get; set; }
        public string ToAddressName { get; set; }
        public string FromAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    }
}
